- [Terraform Beginner Bootcamp 2023 - week0](#terraform-beginner-bootcamp-2023---week0)


  * [Semantic Versioning :mage:](#semantic-versioning--mage-)
  * [Install the Terraform CLI](#install-the-terraform-cli)
    + [Considerations for Linux Distributions](#considerations-for-linux-distributions)
    + [Refactoring into Bash Scripts](#refactoring-into-bash-scripts)
    + [Shebang Considerations](#shebang-considerations)
  * [Execution Considerations](#execution-considerations)
      - [Linux Permission Considerations](#linux-permission-considerations)
    + [Github Lifecycle (Before, Init, Command)](#github-lifecycle--before--init--command-)
    + [Working with Env Vars](#working-with-env-vars)
      - [env command](#env-command)
      - [Setting and Unsetting Env Vars](#setting-and-unsetting-env-vars)
  * [Printing Env Vars](#printing-env-vars)
      - [Scoping of Env Vars](#scoping-of-env-vars)
      - [Persisting Env Vars in Gitpod](#persisting-env-vars-in-gitpod)
    + [AWS CLI Installation](#aws-cli-installation)
  * [Terraform Basics](#terraform-basics)
    + [Terraform Registry](#terraform-registry)
    + [Terraform Console](#terraform-console)
      - [Terraform Init](#terraform-init)
      - [Terraform Plan](#terraform-plan)
      - [Terraform Apply](#terraform-apply)
      - [Terraform Destroy](#terraform-destroy)
    + [Terraform Lock Files](#terraform-lock-files)
    + [Terraform State Files](#terraform-state-files)
    + [Terraform Directory](#terraform-directory)
      - [Issues with Terraform Cloud Login and Gitpod Workspaces](#issues-with-terraform-cloud-login-and-gitpod-workspaces)
